"use client";

import React, { useState } from "react";
import { AnalysisResult, SummaryLength } from "@/lib/types";
import {
  FileText,
  CheckCircle,
  Lightbulb,
  Sparkles,
  Copy,
  Check,
  Download,
  RotateCcw,
  BookOpen,
} from "lucide-react";

interface SummaryResultsProps {
  result: AnalysisResult;
  fileName: string;
  summaryLength: SummaryLength;
  onReset: () => void;
}

export const SummaryResults: React.FC<SummaryResultsProps> = ({
  result,
  fileName,
  summaryLength,
  onReset,
}) => {
  const [copied, setCopied] = useState(false);

  const handleCopySummary = async () => {
    const textToCopy = `DOCUMENT SUMMARY: ${fileName}\nLength: ${summaryLength.toUpperCase()}\n\n--- SUMMARY ---\n${result.summary}\n\n--- KEY POINTS ---\n${result.keyPoints.map((kp) => `• ${kp}`).join("\n")}\n\n--- MAIN IDEAS ---\n${result.mainIdeas.map((mi) => `• ${mi}`).join("\n")}\n\n--- IMPROVEMENT SUGGESTIONS ---\n${result.improvementSuggestions.length > 0 ? result.improvementSuggestions.map((s) => `• ${s}`).join("\n") : "None noted."}`;

    try {
      await navigator.clipboard.writeText(textToCopy);
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    } catch (err) {
      console.error("Failed to copy text: ", err);
    }
  };

  const handleDownloadMarkdown = () => {
    const markdownContent = `# Document Summary Report

**File:** ${fileName}  
**Date:** ${new Date().toLocaleDateString()}  
**Detail Level:** ${summaryLength.toUpperCase()}  

---

## Executive Summary
${result.summary}

---

## Key Points
${result.keyPoints.map((kp) => `- ${kp}`).join("\n")}

---

## Main Ideas & Themes
${result.mainIdeas.map((mi) => `- ${mi}`).join("\n")}

---

## Improvement Suggestions
${
  result.improvementSuggestions.length > 0
    ? result.improvementSuggestions.map((s) => `- ${s}`).join("\n")
    : "*No critical document improvements noted.*"
}

---
*Generated by DocSummary AI using Google Gemini Multimodal API.*
`;

    const blob = new Blob([markdownContent], { type: "text/markdown;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `${fileName.replace(/\.[^/.]+$/, "")}_summary.md`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadJson = () => {
    const jsonContent = JSON.stringify(
      {
        fileName,
        summaryLength,
        generatedAt: new Date().toISOString(),
        analysis: result,
      },
      null,
      2
    );

    const blob = new Blob([jsonContent], { type: "application/json;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `${fileName.replace(/\.[^/.]+$/, "")}_summary.json`;
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="w-full space-y-6 animate-fadeIn">
      {/* Result Header Bar */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 p-5 rounded-2xl bg-slate-900/80 border border-slate-800 shadow-lg">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <span className="text-xs font-semibold px-2.5 py-0.5 rounded-full bg-indigo-500/20 text-indigo-300 border border-indigo-500/30 uppercase tracking-wider">
              {summaryLength} summary
            </span>
            <span className="text-xs text-slate-400">Analysis Complete</span>
          </div>
          <h2 className="text-base font-bold text-slate-100 truncate max-w-md">
            {fileName}
          </h2>
        </div>

        <div className="flex items-center flex-wrap gap-2 w-full sm:w-auto">
          <button
            onClick={handleCopySummary}
            type="button"
            className="flex-1 sm:flex-none flex items-center justify-center gap-1.5 px-3 py-2 rounded-xl text-xs font-semibold bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-700 transition-colors"
          >
            {copied ? (
              <>
                <Check className="h-4 w-4 text-emerald-400" />
                <span>Copied!</span>
              </>
            ) : (
              <>
                <Copy className="h-4 w-4 text-slate-400" />
                <span>Copy</span>
              </>
            )}
          </button>

          <button
            onClick={handleDownloadMarkdown}
            type="button"
            className="flex-1 sm:flex-none flex items-center justify-center gap-1.5 px-3 py-2 rounded-xl text-xs font-semibold bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-700 transition-colors"
            title="Download Markdown"
          >
            <Download className="h-4 w-4 text-slate-400" />
            <span>.MD</span>
          </button>

          <button
            onClick={handleDownloadJson}
            type="button"
            className="flex-1 sm:flex-none flex items-center justify-center gap-1.5 px-3 py-2 rounded-xl text-xs font-semibold bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-700 transition-colors"
            title="Download Raw JSON"
          >
            <Download className="h-4 w-4 text-slate-400" />
            <span>JSON</span>
          </button>

          <button
            onClick={onReset}
            type="button"
            className="flex-1 sm:flex-none flex items-center justify-center gap-1.5 px-3.5 py-2 rounded-xl text-xs font-semibold bg-indigo-600 hover:bg-indigo-500 text-white shadow-md shadow-indigo-600/20 transition-all"
          >
            <RotateCcw className="h-4 w-4" />
            <span>Generate Again</span>
          </button>
        </div>
      </div>

      {/* Main Grid Results */}
      <div className="grid grid-cols-1 gap-6">
        {/* Executive Summary Card */}
        <div className="rounded-2xl bg-slate-900/60 border border-slate-800 p-6 shadow-md backdrop-blur-md">
          <div className="flex items-center gap-2.5 mb-4 pb-3 border-b border-slate-800">
            <div className="p-2 rounded-lg bg-indigo-500/10 text-indigo-400 border border-indigo-500/20">
              <FileText className="h-5 w-5" />
            </div>
            <h3 className="text-base font-bold text-slate-100">Executive Summary</h3>
          </div>
          <div className="text-sm text-slate-300 leading-relaxed space-y-3 whitespace-pre-line">
            {result.summary}
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {/* Key Points Card */}
          <div className="rounded-2xl bg-slate-900/60 border border-slate-800 p-6 shadow-md backdrop-blur-md">
            <div className="flex items-center gap-2.5 mb-4 pb-3 border-b border-slate-800">
              <div className="p-2 rounded-lg bg-emerald-500/10 text-emerald-400 border border-emerald-500/20">
                <CheckCircle className="h-5 w-5" />
              </div>
              <h3 className="text-base font-bold text-slate-100">Key Points</h3>
            </div>
            {result.keyPoints.length > 0 ? (
              <ul className="space-y-2.5 text-sm text-slate-300">
                {result.keyPoints.map((point, i) => (
                  <li key={i} className="flex items-start gap-2.5">
                    <span className="h-1.5 w-1.5 rounded-full bg-emerald-400 mt-2 shrink-0" />
                    <span>{point}</span>
                  </li>
                ))}
              </ul>
            ) : (
              <p className="text-xs text-slate-400 italic">No specific key points extracted.</p>
            )}
          </div>

          {/* Main Ideas Card */}
          <div className="rounded-2xl bg-slate-900/60 border border-slate-800 p-6 shadow-md backdrop-blur-md">
            <div className="flex items-center gap-2.5 mb-4 pb-3 border-b border-slate-800">
              <div className="p-2 rounded-lg bg-purple-500/10 text-purple-400 border border-purple-500/20">
                <BookOpen className="h-5 w-5" />
              </div>
              <h3 className="text-base font-bold text-slate-100">Main Ideas & Themes</h3>
            </div>
            {result.mainIdeas.length > 0 ? (
              <ul className="space-y-2.5 text-sm text-slate-300">
                {result.mainIdeas.map((idea, i) => (
                  <li key={i} className="flex items-start gap-2.5">
                    <span className="h-1.5 w-1.5 rounded-full bg-purple-400 mt-2 shrink-0" />
                    <span>{idea}</span>
                  </li>
                ))}
              </ul>
            ) : (
              <p className="text-xs text-slate-400 italic">No specific main ideas extracted.</p>
            )}
          </div>
        </div>

        {/* Improvement Suggestions Card */}
        <div className="rounded-2xl bg-slate-900/60 border border-slate-800 p-6 shadow-md backdrop-blur-md">
          <div className="flex items-center gap-2.5 mb-4 pb-3 border-b border-slate-800">
            <div className="p-2 rounded-lg bg-amber-500/10 text-amber-400 border border-amber-500/20">
              <Lightbulb className="h-5 w-5" />
            </div>
            <div>
              <h3 className="text-base font-bold text-slate-100">Improvement Suggestions</h3>
              <p className="text-xs text-slate-400">
                Constructive feedback on structure, clarity, or presentation (only provided when meaningful)
              </p>
            </div>
          </div>

          {result.improvementSuggestions && result.improvementSuggestions.length > 0 ? (
            <ul className="space-y-2.5 text-sm text-slate-300">
              {result.improvementSuggestions.map((suggestion, i) => (
                <li key={i} className="flex items-start gap-2.5 bg-slate-800/40 p-3 rounded-xl border border-slate-800">
                  <Sparkles className="h-4 w-4 text-amber-400 shrink-0 mt-0.5" />
                  <span>{suggestion}</span>
                </li>
              ))}
            </ul>
          ) : (
            <div className="p-4 rounded-xl bg-slate-800/30 border border-slate-800 text-center">
              <p className="text-xs text-slate-400">
                ✨ No critical document improvements noted. The document appears well-structured and clear.
              </p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
